### ISSUE TITLE
Selected tab is not visible

### ISSUE THREAD

**Issue by emma28** [28msec/nolap-report-editor#74] opened 2014-07-22 23:42 UTC
When editing a rule or a validation formula, the selected tab is no longer marked:

![image](https://cloud.githubusercontent.com/assets/6932941/3666843/ce2ce5da-11f7-11e4-8828-b75b6f7fa533.png)

**Comment by wcandillon** [comment] 2014-07-23 02:54
duplicate of #36

**Closed as completed by wcandillon** 2014-07-23 02:54 UTC
Labels: duplicate
